version: "2"
services:
  zookeeper1:
    image: registry.cn-hangzhou.aliyuncs.com/chs/data:zk
    ports:
      - "2181:2181"
      - "2881:2881"
      - "3881:3881"
    tty: true
    privileged: true
    command: /opt/zk/zookeeper-3.4.14/bin/zkServer.sh start-foreground
    volumes: 
      - ./local/zk1:/var/cc/zk:rw
      - ./local/zk2/zoo.cfg:/opt/zk/zookeeper-3.4.14/conf/zoo.cfg
  zookeeper2:
    image: registry.cn-hangzhou.aliyuncs.com/chs/data:zk
    ports:
      - "2182:2182"
      - "2882:2882"
      - "3882:3882"
    tty: true
    privileged: true
    command: /opt/zk/zookeeper-3.4.14/bin/zkServer.sh start-foreground
    volumes: 
      - ./local/zk2:/var/cc/zk:rw
      - ./local/zk2/zoo.cfg:/opt/zk/zookeeper-3.4.14/conf/zoo.cfg
  zookeeper3:
    image: registry.cn-hangzhou.aliyuncs.com/chs/data:zk
    ports:
      - "2183:2183"
      - "2883:2883"
      - "3883:3883"
    tty: true
    privileged: true
    command: /opt/zk/zookeeper-3.4.14/bin/zkServer.sh start-foreground
    volumes: 
      - ./local/zk3:/var/cc/zk:rw
      - ./local/zk2/zoo.cfg:/opt/zk/zookeeper-3.4.14/conf/zoo.cfg
  zookeeper4:
    image: registry.cn-hangzhou.aliyuncs.com/chs/data:zk
    ports:
      - "2184:2184"
      - "2884:2884"
      - "3884:3884"
    tty: true
    privileged: true
    command: /opt/zk/zookeeper-3.4.14/bin/zkServer.sh start-foreground
    volumes: 
      - ./local/zk4:/var/cc/zk:rw
      - ./local/zk2/zoo.cfg:/opt/zk/zookeeper-3.4.14/conf/zoo.cfg
